= Cassandra Quickstart

== STEP 1: GET CASSANDRA USING DOCKER

You'll need Docker Desktop for Mac, Docker Desktop for Windows, or an
equivalent Docker installation on Linux.

Apache Cassandra is also available as a tarball or package; see the
xref:installing/installing.adoc[installation guide].

[source,console]
----
include::cassandra:example$BASH/docker_pull.sh[]
----

== STEP 2: START CASSANDRA

A Docker network lets you reach the container ports without publishing
them on the host.

[source,console]
----
include::cassandra:example$BASH/docker-network-run.sh[]
----

== STEP 3: CREATE FILES

Create a file named `data.cql` and paste the following CQL script in it.
The script creates a keyspace, a table, and sample rows:

[source,cql]
----
include::cassandra:example$CQL/create-keyspace-store.cql[]

include::cassandra:example$CQL/create-table-shopping-cart.cql[]

include::cassandra:example$CQL/insert-shopping-cart-data.cql[]
----

== STEP 4: LOAD DATA WITH CQLSH

Use `cqlsh` to load the script into the running container.

[source,console]
----
include::cassandra:example$BASH/docker-run-cqlsh-load-data.sh[]
----

[NOTE]
====
The Cassandra server can take a few seconds to finish starting. If the
load step fails immediately, wait for the node to finish init and retry.
====

== STEP 5: INTERACTIVE CQLSH

You can also use `cqlsh` interactively:

[source,console]
----
include::cassandra:example$BASH/docker-run-cqlsh-quickstart.sh[]
----

This should get you a prompt like this:

[source,console]
----
include::cassandra:example$RESULTS/docker-run-cqlsh-quickstart.result[]
----

== STEP 6: READ SOME DATA

[source,cql]
----
include::cassandra:example$CQL/select-data-from-shopping-cart.cql[]
----

== STEP 7: WRITE SOME MORE DATA

[source,cql]
----
include::cassandra:example$CQL/insert-more-data-shopping-cart.cql[]
----

== STEP 8: CHECK STATUS

Before you clean up, confirm the node is healthy. `nodetool status`
should show the node as `UN`:

[source,console]
----
$ nodetool status
Datacenter: dc1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens  Owns (effective)  Host ID                               Rack
UN  127.0.0.1   123.45 KiB  1       100.0%            01234567-89ab-cdef-0123-456789abcdef  rack1
----

== STEP 9: CLEAN UP

[source,console]
----
include::cassandra:example$BASH/docker-kill-and-remove.sh[]
----

This removes the container and the `cassandra` Docker network created
for the quickstart.

== CONGRATULATIONS!

To learn more, read the xref:master@_:ROOT:cassandra-basics.adoc[Cassandra
Basics] and xref:master@_:ROOT:case-studies.adoc[Case Studies].
